### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by sinclairzx81** [akutruff/typescript-needs-types#1]
Thanks for the project mention and thanks for consolidating all the options out there. It's great to see a list of the community projects all in one place. Great work.

Just a quick thing, would it be possible to rename tsbox to typebox (that's a project I'm maintaining) Also as possible a suggestion, I wonder if it might be good to group projects based on their approach. There are two main approaches that I'm currently aware of.

- Compile Time Transformations | Build tooling.
- Type Mapping | Conditional Types.

Having a quick list of available options grouped this way might be helpful for others looking to approach runtime type validation in TypeScript.

Thanks again!

**Comment by akutruff** [comment]
Great feedback, and will update typebox right now!  I'll start separating them out as well.  It will help people when considering their options.

**Comment by akutruff** [comment]
Fixed!
