### ISSUE TITLE
Found two more: cleaners and type-check

### ISSUE THREAD

**Issue by smichel17** [akutruff/typescript-needs-types#5]
- https://github.com/swansontec/cleaners
- https://github.com/gkz/type-check

**Comment by akutruff** [comment]
Thanks! merged

**Comment by smichel17** [comment]
(I think maybe you meant to post that in #4)

**Comment by akutruff** [comment]
Oh, my bad.  I just submitted these into index.md regardless.  Thanks for contributing!
