### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by cbn-falias** [akutruff/typescript-needs-types#6]
What about those two?
https://github.com/gristlabs/ts-interface-builder
https://github.com/gristlabs/ts-interface-checker

**Comment by marcj** [comment]
Not a great solution if you ask me. It adds a substantial amount of additional runtime code that makes the emitted JS much bigger, slower, and costs more memory. I'd prefer a solution that has almost zero runtime performance impact and only generates load when you actually access the type information.
